name: Python package
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup
        run: sudo apt update && sudo apt install gobject-introspection

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --ignore=E402,W503 --max-complexity=10 --max-line-length=127 --statistics
